services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: nurseydb
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - springboot-mysql-net

  springbootapp:
    image: hemanth1845/nursery-backend:latest
    container_name: springbootapp
    restart: always
    depends_on:
      - mysql
    ports:
      - "2025:2096"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/nurseydb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
    networks:
      - springboot-mysql-net

  reactapp:
    image: hemanth1845/nursery-frontend:latest
    container_name: reactapp
    restart: always
    depends_on:
      - springbootapp
    ports:
      - "8000:80"
    networks:
      - springboot-mysql-net

volumes:
  mysql_data:

networks:
  springboot-mysql-net:
    driver: bridge
